---
- name: converge | all
  hosts: all
  remote_user: root
  become: true
  gather_facts: true

  tasks:
    - name: Apply php role
      ansible.builtin.include_role:
        name: ansible-role-php
      vars:  
        php_version: 8.4.16
    
    - name: Show message
      ansible.builtin.debug:
        msg: "Converge task executed."